#!/bin/sh
# Set up environment
# Source this file using a bash/sh compatible shell, to get an environment,
# where you use the binaries and libraries for this melt build.
INSTALL_DIR=$(pwd)
export PATH="$INSTALL_DIR/bin":$PATH
export LD_LIBRARY_PATH="$INSTALL_DIR/lib":$LD_LIBRARY_PATH
export MLT_REPOSITORY="$INSTALL_DIR/lib/mlt-7"
export MLT_DATA="$INSTALL_DIR/share/mlt-7"
export MLT_PROFILES_PATH="$INSTALL_DIR/share/mlt-7/profiles"
export MLT_MOVIT_PATH="$INSTALL_DIR/share/movit"
export FREI0R_PATH="$INSTALL_DIR/lib/frei0r-1"
# Temporarily ignore user and default path because csladspa bug is crashing with
# LADSPA_PATH set, and Shotcut only needs the supplied SWH plugins.
# export LADSPA_PATH="$LADSPA_PATH:/usr/local/lib/ladspa:/usr/lib/ladspa:/usr/lib64/ladspa:$INSTALL_DIR/lib/ladspa"
export LADSPA_PATH="$INSTALL_DIR/lib/ladspa"
export MANPATH=$MANPATH:"$INSTALL_DIR/share/man"
export PKG_CONFIG_PATH="$INSTALL_DIR/lib/pkgconfig":$PKG_CONFIG_PATH
export QT_PLUGIN_PATH="$INSTALL_DIR/lib/qt6"
export QML2_IMPORT_PATH="$INSTALL_DIR/lib/qml"
